@AzureContainerApp.EnvironmentVariables_HostAddress = http://localhost:32776

GET {{AzureContainerApp.EnvironmentVariables_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{AzureContainerApp.EnvironmentVariables_HostAddress}}/api/ship-theory

###
