@AzureContainerApp.EnvironmentVariables_HostAddress = https://localhost:32771

GET {{AzureContainerApp.EnvironmentVariables_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{AzureContainerApp.EnvironmentVariables_HostAddress}}/api/ship-theory

###
